<a href="https://colab.research.google.com/github/salma10102005/ml-course/blob/main/pandas_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

mylist = [100,200,300]

res = pd.Series(mylist)

print(res)



0    100
1    200
2    300
dtype: int64


In [ ]:
import numpy as np

arr = np.array([100,200,300])

res = pd.Series(arr)

print(res)
print(type(res))

0    100
1    200
2    300
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive
import warnings
warnings.filterwarnings('ignore')

print("pandas version:" ,  pd.__version__)
print( "numpy version :" ,  np.__version__)

pandas version: 2.2.2
numpy version : 2.0.2


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("pandas version:" ,  pd.__version__)
print( "numpy version :" ,  np.__version__)

pandas version: 2.2.2
numpy version : 2.0.2


In [ ]:
# creating numing areas

arr1 = np.array([1,2,3,4])
arr2 = np.array([[4 , 5, 6,] , [8 ,9 , 10]])

print("1D array:" , arr1)
print("2D array:" , arr2)

print("shape of 1D array:" , arr1.shape)
print("shape of 2D array:" , arr2.shape)

print("dimension of 1D array:" , arr1.ndim)
print("dimension of 2D array:" , arr2.ndim)

print("size of 1D array:" , arr1.size)
print("size of 2D array:" , arr2.size)

print(arr1.dtype)
print(arr2.dtype)



1D array: [1 2 3 4]
2D array: [[ 4  5  6]
 [ 8  9 10]]
shape of 1D array: (4,)
shape of 2D array: (2, 3)
dimension of 1D array: 1
dimension of 2D array: 2
size of 1D array: 4
size of 2D array: 6
int64
int64


In [ ]:
a = np.zeros((3,4))
b = np.ones((3,4))
c = np.arange(10,25,5)
d = np.linspace(0,2,9)

print(a)
print(b)
print(c)
print(d)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10 ,])

print(a+b)
print(a*b)
print(np.sqrt(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

vector = np.array([10,20,30])

result = matrix + vector
print(result)


[ 7  9 11 13 15]
[ 6 14 24 36 50]
[1.         1.41421356 1.73205081 2.         2.23606798]
3.0
1.4142135623730951
1
5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore')


Mounted at /content/drive


In [ ]:
# Step 1: import libraries
import pandas as pd

# Step 2: load dataset (CSV is in /content)
file_path = "/content/diabetes.csv"
df = pd.read_csv(file_path)

# Step 3: confirm loading
print("Dataset loaded successfully!")
print("Shape:", df.shape)

# Step 4: show first 5 rows
df.head()


Dataset loaded successfully!
Shape: (768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
import pandas as pd
df = pd.read_csv('/content/heart.csv')

print(df.shape)
df.head()


(1025, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
print(df.head)
print(df.tail)
print(df.info)
print(df.describe)

<bound method NDFrame.head of      Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50 